require "pry"
require "nokogiri"
require "open-uri"
require_relative "run.rb"
# require_relative "car.rb"

# require_relative "scraper.rb"
#require_relative "run.rb"
# require_relative "year.rb"
 require_relative "cli.rb"